name: Node.js CI

on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: npm install
      - run : npm install
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: divya-gariga/counter-app/counterapp
          registry: ghcr.io
          username: divya-gariga
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
      - name: Install npm
        run: npm install
      - name: run test cases
        run: npm test
