name: Node.js CI

on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login to github container registry
        run: docker login ${{ env.GITHUB_PACKAGE_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_TOKEN }}
      - name: docker build
        run: docker build . -t ghcr.io/divya-gariga/counter-app:latest
      - name: docker push
        run: docker push ghcr.io/divya-gariga/counter-app:latest
      - name: run test cases
        run: npm test
