name: Node.js CI

on:
 push:
  branches:
  - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - run: npm run build --if-present
      - run: npm test

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: my_github_username/my_repository_name/my_image_name
          registry: ghcr.io
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: Dockerfile
          tags: |
            ghcr.io/divya-gariga/counter-app/counterapp:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

